# Generated by Django 4.2.29 on 2026-05-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('security', 'Security Personnel'), ('vehicle_owner', 'Registered Vehicle Owner')], default='vehicle_owner', max_length=20),
        ),
    ]
