# Generated by Django 6.0.5 on 2026-06-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_gate_qrtoken_guardshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus_days',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('admin_replaced', 'Admin Replaced'), ('scan', 'Vehicle Scanned'), ('vehicle_entered', 'Vehicle Entered'), ('vehicle_exited', 'Vehicle Exited'), ('visitor_issued', 'Visitor Pass Issued'), ('visitor_exited', 'Visitor Exited'), ('entry_override', 'Entry Override')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='schedule',
            field=models.CharField(blank=True, choices=[('MWF', 'Monday-Wednesday-Friday'), ('TTHS', 'Tuesday-Thursday-Saturday'), ('MIXED', 'Custom / Mixed Days'), ('ANY', 'Any Day'), ('ALL', 'All Days')], max_length=10, null=True),
        ),
    ]
