# Generated by Django 4.2.30 on 2026-07-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_campus_days_to_user'),
        ('accounts', '0011_user_guard_qr_secret_alter_auditlog_action'),
    ]

    operations = [
    ]
