# Generated by Django 4.2.30 on 2026-07-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20260701_1620'),
        ('accounts', '0013_remove_demo_users'),
    ]

    operations = [
    ]
