# Generated by Django 6.0.5 on 2026-07-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_violation_issued_audit_action'),
        ('accounts', '0014_merge_0012_merge_20260701_1620_0013_remove_demo_users'),
    ]

    operations = [
    ]
