# Generated by Django 6.0.5 on 2026-07-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20260702_0335'),
        ('accounts', '0015_merge_20260702_0730'),
    ]

    operations = [
    ]
