# Generated by Django 6.0.5 on 2026-07-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20260702_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('admin_replaced', 'Admin Replaced'), ('scan', 'Vehicle Scanned'), ('vehicle_entered', 'Vehicle Entered'), ('vehicle_exited', 'Vehicle Exited'), ('visitor_issued', 'Visitor Pass Issued'), ('visitor_exited', 'Visitor Exited'), ('entry_override', 'Entry Override')], max_length=30),
        ),
    ]
