# Generated by Django 4.2.30 on 2026-07-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_auditlog_action'),
        ('accounts', '0017_alter_auditlog_action'),
    ]

    operations = [
    ]
