# Generated by Django 6.0.5 on 2026-07-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_auditlog_action'),
        ('accounts', '0017_alter_auditlog_action'),
    ]

    operations = [
    ]
