# Generated by Django 4.2.30 on 2026-07-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20260703_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
