# Generated by Django 6.0.5 on 2026-07-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_auditlog_action'),
        ('accounts', '0019_user_agency'),
    ]

    operations = [
    ]
