# Generated by Django 6.0.5 on 2026-07-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_0019_alter_auditlog_action_0019_user_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(db_column='audit_log_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(db_column='user_id', primary_key=True, serialize=False),
        ),
    ]
