# Generated by Django 4.2.30 on 2026-07-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gate_assignment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
