# Generated by Django 6.0.5 on 2026-07-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_cdso_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='tbl_audit_log',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='tbl_notification',
        ),
        migrations.AlterModelTable(
            name='user',
            table='tbl_user',
        ),
    ]
