# Generated by Django 4.2.30 on 2026-07-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_options_alter_auditlog_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('security', 'Security Personnel'), ('vehicle_owner', 'Registered Vehicle Owner'), ('cdso', 'CDSO Staff')], default='vehicle_owner', max_length=20),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
