# Generated by Django 6.0.5 on 2026-07-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_restore_tbl_naming'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expires_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('user_archived', 'Account Auto-Archived (Expired)'), ('admin_replaced', 'Admin Replaced'), ('scan', 'Vehicle Scanned'), ('vehicle_entered', 'Vehicle Entered'), ('vehicle_exited', 'Vehicle Exited'), ('visitor_issued', 'Visitor Pass Issued'), ('visitor_exited', 'Visitor Exited'), ('entry_override', 'Entry Override'), ('created', 'Record Created'), ('updated', 'Record Updated'), ('deleted', 'Record Deleted')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('email',), name='uniq_active_user_email'),
        ),
    ]
