# Generated by Django 6.0.5 on 2026-07-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_user_archived_at_user_expires_at_user_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_banned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
