# Generated by Django 6.0.5 on 2026-08-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_user_registration_banned'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('is_archived', True)), fields=['archived_at'], name='user_archived_at'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('is_active', True), ('is_archived', False)), fields=['expires_at'], name='user_expiry_due'),
        ),
    ]
