# Generated by Django 6.0.5 on 2026-08-13 10:20

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_user_user_archived_at_user_user_expiry_due'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Upper('email'), name='user_email_upper'),
        ),
    ]
