# Generated by Django 6.0.5 on 2026-08-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_user_user_email_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confiscated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confiscated_until',
            field=models.DateField(blank=True, db_index=True, help_text='Last day of the penalty, inclusive. NULL while a level is set means indefinite (until the CDSO lifts it).', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confiscation_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = not confiscated. 1, 2 or 3 = which offence imposed it.'),
        ),
        migrations.AddField(
            model_name='user',
            name='confiscation_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
