# Generated by Django 6.0.5 on 2026-08-18 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_rename_user_m2m_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('user_archived', 'Account Auto-Archived (Expired)'), ('admin_replaced', 'Admin Replaced'), ('twofa_enabled', 'Two-Factor Enabled'), ('twofa_disabled', 'Two-Factor Disabled'), ('twofa_reset', 'Two-Factor Reset by Admin'), ('twofa_failed', 'Two-Factor Verification Failed'), ('twofa_backup_used', 'Two-Factor Backup Code Used'), ('scan', 'Vehicle Scanned'), ('vehicle_entered', 'Vehicle Entered'), ('vehicle_exited', 'Vehicle Exited'), ('visitor_issued', 'Visitor Pass Issued'), ('visitor_exited', 'Visitor Exited'), ('entry_override', 'Entry Override'), ('created', 'Record Created'), ('updated', 'Record Updated'), ('deleted', 'Record Deleted')], max_length=30),
        ),
        migrations.CreateModel(
            name='TwoFactorDevice',
            fields=[
                ('id', models.BigAutoField(db_column='two_factor_device_id', primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_step', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twofa_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_two_factor_device',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorBackupCode',
            fields=[
                ('id', models.BigAutoField(db_column='two_factor_backup_code_id', primary_key=True, serialize=False)),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twofa_backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_two_factor_backup_code',
                'indexes': [models.Index(condition=models.Q(('used_at__isnull', True)), fields=['user'], name='twofa_backup_unused')],
            },
        ),
    ]
