# Generated by Django 6.0.5 on 2026-08-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_auditlog_action_twofactordevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_verify_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
