# Generated by Django 6.0.5 on 2026-08-19 10:55
"""Take vehicle-owner gate movement out of the audit log.

The audit log is the administrative accountability trail. It had also been
recording every scan, entry and exit — plate, owner name, gate and dwell time —
which made an admin-only screen into a searchable, exportable movement profile
of every registered driver, beyond what the campus privacy notice covers. That
history already exists in scanning.AccessLog for gate operations, so it is
removed here rather than merely hidden.

Guard shift sign-ins had been filed under the same 'scan' action even though
they are staff authentication, not vehicle activity. They are re-pointed to the
new 'guard_login' action *before* the purge so that trail survives.
"""

from django.db import migrations, models


# Actions that recorded where an owner went. Dropped from the model, and their
# rows deleted below.
MOVEMENT_ACTIONS = ['scan', 'vehicle_entered', 'vehicle_exited']

# The three guard sign-in paths (QRLoginView, GuardCredentialLoginView and the
# gate-kiosk shift login) all wrote action='scan' with one of these prefixes.
GUARD_LOGIN_PREFIXES = ['Guard shift login', 'Guard QR login', 'Guard credential login']


def forwards(apps, schema_editor):
    AuditLog = apps.get_model('accounts', 'AuditLog')

    for prefix in GUARD_LOGIN_PREFIXES:
        AuditLog.objects.filter(action='scan', details__startswith=prefix).update(
            action='guard_login')

    AuditLog.objects.filter(action__in=MOVEMENT_ACTIONS).delete()


def backwards(apps, schema_editor):
    """Deleted movement rows are gone for good; only the relabel is reversible."""
    AuditLog = apps.get_model('accounts', 'AuditLog')
    AuditLog.objects.filter(action='guard_login').update(action='scan')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_user_must_verify_2fa'),
    ]

    operations = [
        # Relabel + purge first: the rows must stop existing under the old
        # action values before the field's choices no longer include them.
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('user_archived', 'Account Auto-Archived (Expired)'), ('admin_replaced', 'Admin Replaced'), ('twofa_enabled', 'Two-Factor Enabled'), ('twofa_disabled', 'Two-Factor Disabled'), ('twofa_reset', 'Two-Factor Reset by Admin'), ('twofa_failed', 'Two-Factor Verification Failed'), ('twofa_backup_used', 'Two-Factor Backup Code Used'), ('guard_login', 'Guard Shift Login'), ('visitor_issued', 'Visitor Pass Issued'), ('visitor_exited', 'Visitor Exited'), ('entry_override', 'Entry Override'), ('created', 'Record Created'), ('updated', 'Record Updated'), ('deleted', 'Record Deleted')], max_length=30),
        ),
    ]
