# Generated by Django 4.2.30 on 2026-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_split_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owner_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('fetcher', 'Fetcher / Drop & Go / Parent'), ('employee', 'Employee'), ('visitor', 'Visitor')], max_length=20, null=True),
        ),
    ]
