"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(name, default='false'):
    return os.getenv(name, default).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=''):
    return [v.strip() for v in os.getenv(name, default).split(',') if v.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# Railway injects these at runtime; their presence is a reliable signal that
# this process is a deployment rather than someone's laptop.
RAILWAY_DOMAIN = os.getenv('RAILWAY_PUBLIC_DOMAIN', '').strip()
ON_RAILWAY = bool(RAILWAY_DOMAIN or os.getenv('RAILWAY_ENVIRONMENT'))

# SECURITY WARNING: don't run with debug turned on in production!
# The default is inverted on Railway: forgetting to set DEBUG should fail
# closed (no stack traces to the public internet), not open. Locally it still
# defaults to True, so the existing dev workflow is unchanged.
DEBUG = _env_bool('DEBUG', 'false' if ON_RAILWAY else 'true')

if not DEBUG and not SECRET_KEY:
    raise RuntimeError('SECRET_KEY must be set when DEBUG is off.')

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')

if RAILWAY_DOMAIN:
    # Saves hand-editing ALLOWED_HOSTS every time the domain changes.
    ALLOWED_HOSTS.append(RAILWAY_DOMAIN)
    # Railway's deploy healthcheck calls in over the internal network with its
    # own Host header; without this the probe 400s and the deploy is marked bad.
    ALLOWED_HOSTS.append('healthcheck.railway.app')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Required for GinIndex on VehicleRegistration.campus_days (JSON containment).
    'django.contrib.postgres',

    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',

    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'vehicles',
    'scanning',
    'violations',
    'realtime',
]

MIDDLEWARE = [
    # First in the list: revive a stale pooled DB connection before anything
    # else (sessions, auth) tries to query with it.
    'config.middleware.IdleConnectionHealthCheckMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serves the built React bundle and Django's own static files straight from
    # the app process — must sit directly after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Compresses JSON payloads; the report/list endpoints shrink by ~80%, which
    # is the difference that shows over a long-haul link.
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Without a default page size every list endpoint serialises the whole
    # table — cost grows with the row count instead of staying flat. Clients
    # that pass no ?page= still get page 1, so responses stay bounded.
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.DefaultPagination',
    'PAGE_SIZE': int(os.getenv('DRF_PAGE_SIZE', 50)),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=int(os.getenv('ACCESS_TOKEN_LIFETIME_MINUTES', 60))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('REFRESH_TOKEN_LIFETIME_DAYS', 7))),
    'ROTATE_REFRESH_TOKENS':  True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

AUTH_USER_MODEL = 'accounts.User'

# User.email intentionally isn't globally unique: an archived (expired) owner
# keeps their email so a new account can reuse it. Uniqueness among *live*
# accounts is enforced by the partial UniqueConstraint `uniq_active_user_email`,
# and UserManager.get_by_natural_key resolves auth to the non-archived row — so
# auth.E003 (USERNAME_FIELD must be unique) is handled and safely silenced.
SILENCED_SYSTEM_CHECKS = ['auth.E003']

# A Redis channel layer is what makes `broadcast_change` actually reach
# browsers: the in-memory layer is per-process, so anything sent from the
# Celery worker (a separate process) was being dropped on the floor, and any
# second web replica would only notify the clients attached to itself.
# Falls back to in-memory when no Redis is configured, so local dev without a
# broker keeps working.
#
# It is also what links the campus and Railway halves. They already share one
# database, so data is identical the instant it is written — but a browser
# sitting on a page is only *told* by the half it is connected to. Point both
# halves at the SAME Redis (REDIS_URL) and a scan at the gate refreshes an
# off-campus screen live. The fan-out group is a single constant ("updates",
# realtime/broadcast.py) with no per-instance scoping, so this needs no code
# change — only a Redis both halves can reach. `rediss://` (TLS) is supported,
# which is how a managed provider works without a raw TCP proxy.
REDIS_URL = os.getenv('REDIS_URL') or os.getenv('CELERY_BROKER_URL', '')

# A loopback Redis cannot be shared between two machines, and pointing the
# channel layer at one that is not running fails *silently*: broadcast_change
# swallows the error by design, so live updates simply stop with no message.
# This is the trap when linking the two halves — CELERY_BROKER_URL commonly
# still holds a dev-time redis://127.0.0.1, and it is picked up above whenever
# REDIS_URL is unset or misspelled.
REDIS_IS_LOOPBACK = any(h in REDIS_URL for h in ('127.0.0.1', 'localhost', '::1'))
REALTIME_CROSS_HOST = bool(REDIS_URL) and not REDIS_IS_LOOPBACK

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL], 'capacity': 1500, 'expiry': 10},
        },
    }
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'},
            'KEY_PREFIX': 'slcvms',
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'},
    }
    CACHES = {
        'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'},
    }

# Say plainly which mode is active. Live updates failing is otherwise invisible:
# nothing errors, screens just quietly stop refreshing until someone reloads.
if REALTIME_CROSS_HOST:
    print('[settings] realtime: shared Redis channel layer - live updates reach '
          'BOTH the campus and Railway halves.')
elif REDIS_IS_LOOPBACK:
    print('[settings] realtime: Redis channel layer on a LOOPBACK address - live '
          'updates reach only browsers connected to THIS host. Set REDIS_URL to a '
          'Redis both halves can reach to link them.')
else:
    print('[settings] realtime: in-memory channel layer (no REDIS_URL) - live '
          'updates reach only this process. Set REDIS_URL to link the two halves.')

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

_db_url = os.getenv('DATABASE_URL')
if _db_url:
    DATABASES = {'default': dj_database_url.parse(_db_url, conn_max_age=600, ssl_require=True)}
    # Neon is reached through its pgbouncer endpoint (-pooler), which runs in
    # transaction pooling mode. Django does not support server-side cursors
    # there — a named cursor can land on a different backend connection than
    # the one that declared it. QuerySet.iterator() silently falls back to
    # client-side fetching once this is set.
    #
    # It is also a large speed win over a long-haul link: a server-side cursor
    # costs DECLARE + repeated FETCH + CLOSE, and every one of those is a
    # separate round trip to Singapore.
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'plate_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'password'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Campus wall-clock — schedule rules (campus days, time windows) and
# "today" boundaries are evaluated in this timezone. DB storage stays UTC.
TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── Built React bundle ────────────────────────────────────────────────────────
# The Docker build drops Vite's output here. WhiteNoise serves it at the web
# root, so the SPA and the API share one origin: axios' relative '/api' baseURL
# works untouched, there is no CORS preflight on any request, and there is a
# single Railway URL to open. Empty in local dev (Vite serves the app itself).
FRONTEND_BUILD_DIR = BASE_DIR / 'frontend_build'
WHITENOISE_ROOT = FRONTEND_BUILD_DIR if FRONTEND_BUILD_DIR.exists() else None
# index.html must stay uncached or browsers pin a stale bundle across deploys;
# the hashed files under /assets/ are safe to cache forever.
WHITENOISE_INDEX_FILE = True
WHITENOISE_MAX_AGE = 31536000
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'zip',
                                       'gz', 'tgz', 'bz2', 'tbz', 'xz', 'br', 'pt']

# CompressedStaticFilesStorage, not the *Manifest* variant: the manifest raises
# a hard 500 on any unresolved reference in a CSS/JS file, which is a common way
# for a deploy to come up broken. Compression is the part that matters here —
# the React bundle's cache-busting comes from Vite's content hashes.
_STATIC_BACKEND = (
    'whitenoise.storage.CompressedStaticFilesStorage' if not DEBUG
    else 'django.contrib.staticfiles.storage.StaticFilesStorage'
)

if os.getenv('USE_R2', 'false').lower() == 'true':
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {"BACKEND": _STATIC_BACKEND},
    }
    AWS_ACCESS_KEY_ID       = os.getenv('R2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY   = os.getenv('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('R2_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL     = f"https://{os.getenv('R2_ACCOUNT_ID')}.r2.cloudflarestorage.com"
    AWS_S3_REGION_NAME      = 'auto'
    AWS_DEFAULT_ACL         = 'public-read'
    AWS_S3_FILE_OVERWRITE   = False
    AWS_QUERYSTRING_AUTH    = False
    # R2 public files are served from the bucket's r2.dev (or custom) domain, not
    # the S3 API endpoint. Point .url() at that public host so evidence images
    # load in the browser. R2_PUBLIC_URL may already include the scheme.
    _r2_public_host         = os.getenv('R2_PUBLIC_URL', '').replace('https://', '').replace('http://', '').strip('/')
    AWS_S3_CUSTOM_DOMAIN    = _r2_public_host
    MEDIA_URL               = f"https://{_r2_public_host}/"
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": _STATIC_BACKEND},
    }
    if not DEBUG:
        # Railway containers have an ephemeral filesystem: every redeploy wipes
        # MEDIA_ROOT, taking licence photos and violation evidence with it.
        print('[settings] WARNING: USE_R2=false in production - uploaded files '
              'will be lost on every redeploy. Set USE_R2=true.')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER')
EMAIL_TIMEOUT = 10  # seconds — a hung SMTP server must not stall the scan pipeline
BACKEND_URL = os.getenv('BACKEND_URL', 'http://localhost:8000')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 3600
CELERY_WORKER_POOL = os.getenv('CELERY_WORKER_POOL', 'solo')

# ML Feedback Loop Configuration
ML_SAMPLE_BATCH_SIZE = int(os.getenv('ML_SAMPLE_BATCH_SIZE', 50))
ML_AUTO_RETRAIN_ENABLED = os.getenv('ML_AUTO_RETRAIN_ENABLED', 'true').lower() == 'true'

# ── Production hardening ──────────────────────────────────────────────────────
# Everything below is a no-op in local development (DEBUG=True).

# Railway terminates TLS at its edge and forwards plain HTTP to the container.
# Without this header mapping Django believes every request is insecure: it
# would redirect HTTPS traffic into an infinite loop and refuse to set secure
# cookies. This line is what makes the rest of the block safe to enable.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Django requires the scheme on trusted origins. Accepts either a full origin
# or a bare host in CSRF_TRUSTED_ORIGINS, and always trusts the Railway domain.
CSRF_TRUSTED_ORIGINS = [
    o if o.startswith('http') else f'https://{o}'
    for o in _env_list('CSRF_TRUSTED_ORIGINS')
]
if RAILWAY_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_DOMAIN}')

# The SPA is served from the same origin as the API, so no cross-origin request
# is expected in production. CORS_ALLOWED_ORIGINS stays configurable for the
# on-campus scanning agent, which does call in from another host.
CORS_ALLOW_CREDENTIALS = True

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', 'true')
    # Railway's healthcheck probes over plain HTTP internally; redirecting it
    # to HTTPS makes the deploy fail its own health gate.
    SECURE_REDIRECT_EXEMPT = [r'^healthz/?$']
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', 31536000))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SESSION_COOKIE_HTTPONLY = True

# Django's admin lives under a non-default prefix because the React app owns
# the '/admin' route on this shared origin (see config/urls.py).
DJANGO_ADMIN_URL = os.getenv('DJANGO_ADMIN_URL', 'django-admin').strip('/')
