# Generated by Django 6.0.5 on 2026-05-27 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='owners/')),
                ('owner_type', models.CharField(choices=[('student', 'Student'), ('fetcher', 'Fetcher/Dropper'), ('employee', 'Employee'), ('visitor', 'Visitor')], default='student', max_length=20)),
                ('schedule', models.CharField(choices=[('MWF', 'Monday-Wednesday-Friday'), ('TTHS', 'Tuesday-Thursday-Saturday'), ('ANY', 'Any Day')], default='MWF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('van', 'Van'), ('bus', 'Bus')], default='car', max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('is_authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.owner')),
            ],
        ),
    ]
