# Generated by Django 4.2.29 on 2026-06-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_registrationtoken_vehicleregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('constraint_type', models.CharField(choices=[('employee', 'Employee'), ('student', 'Student'), ('visitor', 'Visitor')], max_length=20)),
                ('days', models.JSONField(default=list)),
                ('start_time', models.CharField(default='06:00', max_length=5)),
                ('end_time', models.CharField(default='20:00', max_length=5)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['constraint_type', 'name'],
            },
        ),
    ]
