# Generated by Django 4.2.29 on 2026-06-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_ruleconstraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTypeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.CharField(choices=[('four-wheel', '4-Wheel Vehicles'), ('three-wheel', '3-Wheel Vehicles'), ('two-wheel', '2-Wheel Vehicles'), ('heavy', 'Heavy Vehicles')], max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sub', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Truck', 'Truck')], default='Car', max_length=20)),
                ('gate', models.CharField(choices=[('Main Gate 1', 'Main Gate 1'), ('Main Gate 2', 'Main Gate 2')], default='Main Gate 1', max_length=30)),
                ('is_all_hours', models.BooleanField(default=True)),
                ('hours_start', models.CharField(default='06:00', max_length=5)),
                ('hours_end', models.CharField(default='20:00', max_length=5)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('restricted', 'Restricted Hours')], default='allowed', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordering', 'label'],
            },
        ),
    ]
