# Generated by Django 4.2.29 on 2026-06-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicletypeaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletypeaccess',
            name='category_key',
            field=models.CharField(choices=[('four-wheel', '4-Wheel Vehicles'), ('three-wheel', '3-Wheel Vehicles'), ('two-wheel', '2-Wheel Vehicles'), ('ebike', 'E-Bike'), ('escooter', 'E-Scooter'), ('heavy', 'Heavy Vehicles')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicletypeaccess',
            name='icon',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Truck', 'Truck'), ('Zap', 'Zap')], default='Car', max_length=20),
        ),
    ]
