# Generated by Django 4.2.30 on 2026-06-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicletypeaccess_category_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='system_employee_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='system_student_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
