# Generated by Django 4.2.30 on 2026-06-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_remove_owner_user_code_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='schedule',
            field=models.CharField(choices=[('MWF', 'Monday-Wednesday-Friday'), ('TTHS', 'Tuesday-Thursday-Saturday'), ('ANY', 'Any Day'), ('ALL', 'All Days')], default='MWF', max_length=10),
        ),
    ]
