# Generated by Django 4.2.30 on 2026-06-21 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_registration_updates'),
        ('vehicles', '0011_department_program'),
    ]

    operations = [
    ]
