# Generated by Django 4.2.30 on 2026-06-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_reg_fields_and_schema_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtoken',
            name='registrant_type',
            field=models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('fetcher', 'Fetcher/Drop&Go')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='registrant_type',
            field=models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('fetcher', 'Fetcher/Drop&Go')], max_length=20),
        ),
    ]
