# Generated by Django 4.2.30 on 2026-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_parkingzone_rtsp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingzone',
            name='rtsp_url',
            field=models.CharField(blank=True, help_text='RTSP stream URL, e.g. rtsp://192.168.1.100:554/stream', max_length=500),
        ),
    ]
