# Generated by Django 4.2.30 on 2026-06-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0030_systemsettings_event_mode_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='event_mode_parking',
            field=models.BooleanField(default=False, help_text='When enabled, guards can override full-parking restrictions.'),
        ),
    ]
