# Generated by Django 4.2.29 on 2026-06-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0026_seed_camera_mitzh'),
        ('vehicles', '0031_alter_systemsettings_event_mode_parking'),
    ]

    operations = [
    ]
