# Generated by Django 4.2.29 on 2026-06-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0035_vehicleregistration_special_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='open_campus_mode',
            field=models.BooleanField(default=False, help_text='When enabled, all vehicles are allowed entry regardless of registration or schedule rules.'),
        ),
    ]
