# Generated by Django 6.0.5 on 2026-07-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0039_camera_gate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='schedule',
            field=models.CharField(blank=True, choices=[('MWF', 'Monday-Wednesday-Friday'), ('TTHS', 'Tuesday-Thursday-Saturday'), ('MIXED', 'Mixed / Custom Days'), ('ANY', 'Any Day')], max_length=10),
        ),
    ]
