# Generated by Django 6.0.5 on 2026-07-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0043_alter_systemsettings_scan_dedup_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleconstraint',
            name='max_stay_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum allowed stay in minutes. Exceeding it on exit auto-issues a time-exceed violation. Blank = no stay limit.', null=True),
        ),
        migrations.AlterField(
            model_name='ruleconstraint',
            name='constraint_type',
            field=models.CharField(choices=[('student_vehicle', 'Student — Vehicle'), ('employee', 'Employee'), ('fetcher', 'Fetcher / Drop & Go'), ('supplier', 'Supplier')], max_length=20),
        ),
    ]
