# Generated by Django 6.0.5 on 2026-07-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0044_ruleconstraint_max_stay_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.BigAutoField(db_column='camera_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(db_column='event_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parkingnotice',
            name='id',
            field=models.BigAutoField(db_column='notice_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='id',
            field=models.BigAutoField(db_column='space_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='id',
            field=models.BigAutoField(db_column='zone_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referenceitem',
            name='id',
            field=models.BigAutoField(db_column='reference_item_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrationperiod',
            name='id',
            field=models.BigAutoField(db_column='period_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ruleconstraint',
            name='id',
            field=models.BigAutoField(db_column='rule_constraint_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.BigAutoField(db_column='supplier_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplierplate',
            name='id',
            field=models.BigAutoField(db_column='supplier_plate_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.BigAutoField(db_column='settings_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(db_column='vehicle_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='id',
            field=models.BigAutoField(db_column='registration_id', primary_key=True, serialize=False),
        ),
    ]
