# Generated by Django 4.2.30 on 2026-07-06 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0045_alter_camera_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingzone',
            name='rtsp_url',
        ),
        migrations.AddField(
            model_name='parkingzone',
            name='camera',
            field=models.ForeignKey(blank=True, help_text='Physical camera (registered in Device Management) that watches this zone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_zones', to='vehicles.camera'),
        ),
    ]
