# Generated by Django 6.0.5 on 2026-07-05 10:53

from django.conf import settings
from django.db import migrations, models


ACTIVE = ['pending', 'accepted']


def _normalize_existing(apps, schema_editor):
    """Canonicalize stored plate/email, then close duplicate ACTIVE registrations
    so the unique constraints below can be applied cleanly.

    For each of plate_number and email, the most recent active registration is
    kept; older active duplicates are moved to REJECTED with an explanatory
    reason. Rejected rows are never touched.
    """
    VehicleRegistration = apps.get_model('vehicles', 'VehicleRegistration')

    # 1) Normalize every row (historical model has no custom save()).
    for reg in VehicleRegistration.objects.all().only('pk', 'plate_number', 'email'):
        new_plate = (reg.plate_number or '').strip().upper().replace(' ', '')
        new_email = (reg.email or '').strip().lower()
        if new_plate != reg.plate_number or new_email != reg.email:
            reg.plate_number = new_plate
            reg.email = new_email
            reg.save(update_fields=['plate_number', 'email'])

    # 2) Resolve duplicate active registrations, newest-wins.
    for field in ('email', 'plate_number'):
        seen = set()
        qs = (VehicleRegistration.objects
              .filter(status__in=ACTIVE)
              .order_by('-created_at', '-pk'))
        for reg in qs:
            key = getattr(reg, field)
            if not key:
                continue
            if key in seen:
                reg.status = 'rejected'
                if not reg.rejection_reason:
                    reg.rejection_reason = (
                        'Auto-closed during migration: a newer active registration '
                        'already uses this %s.' % ('email' if field == 'email' else 'plate number')
                    )
                reg.save(update_fields=['status', 'rejection_reason'])
            else:
                seen.add(key)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    # Non-atomic so the data normalization/dedupe commits before the unique
    # indexes are built — Postgres can't CREATE INDEX in the same transaction
    # that still has pending row-change trigger events.
    atomic = False

    dependencies = [
        ('vehicles', '0045_alter_camera_id_alter_event_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_normalize_existing, _noop),
        migrations.AddConstraint(
            model_name='vehicleregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('plate_number',), name='uniq_active_registration_plate'),
        ),
        migrations.AddConstraint(
            model_name='vehicleregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('email',), name='uniq_active_registration_email'),
        ),
    ]
