# Generated by Django 4.2.30 on 2026-07-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0045_alter_camera_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='driver_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='driver_relationship',
            field=models.CharField(blank=True, choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('authorized_driver', 'Authorized Driver')], max_length=30),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='student_level',
            field=models.CharField(blank=True, choices=[('college', 'College'), ('shs', 'Senior High School'), ('jhs', 'Junior High School'), ('elementary', 'Elementary'), ('sped', 'Special Education')], max_length=20),
        ),
    ]
