# Generated by Django 4.2.30 on 2026-07-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0046_remove_parkingzone_rtsp_url_parkingzone_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='points',
            field=models.JSONField(blank=True, help_text='Freeform polygon vertices [[x,y], ...] normalized 0-1 (pen tool). x1..y2 still holds the bounding box for quick lookups.', null=True),
        ),
    ]
