# Generated by Django 6.0.5 on 2026-07-05 11:02

from django.conf import settings
from django.db import migrations, models


ACTIVE = ['pending', 'accepted']


def _normalize_and_dedupe(apps, schema_editor):
    """Canonicalize stored student/employee IDs and driver's licenses, then close
    duplicate ACTIVE registrations (newest-wins) so the unique constraints below
    apply cleanly. Blank values are never treated as duplicates.
    """
    VehicleRegistration = apps.get_model('vehicles', 'VehicleRegistration')

    for reg in VehicleRegistration.objects.all().only(
        'pk', 'student_id', 'employee_id', 'drivers_license'
    ):
        new_student = (reg.student_id or '').strip()
        new_employee = (reg.employee_id or '').strip()
        new_license = (reg.drivers_license or '').strip().upper()
        if (new_student != reg.student_id
                or new_employee != reg.employee_id
                or new_license != reg.drivers_license):
            reg.student_id = new_student
            reg.employee_id = new_employee
            reg.drivers_license = new_license
            reg.save(update_fields=['student_id', 'employee_id', 'drivers_license'])

    labels = {
        'student_id': 'student ID',
        'employee_id': 'employee ID',
        'drivers_license': "driver's license",
    }
    for field in ('student_id', 'employee_id', 'drivers_license'):
        seen = set()
        qs = (VehicleRegistration.objects
              .filter(status__in=ACTIVE)
              .exclude(**{field: ''})
              .order_by('-created_at', '-pk'))
        for reg in qs:
            key = getattr(reg, field)
            if key in seen:
                reg.status = 'rejected'
                if not reg.rejection_reason:
                    reg.rejection_reason = (
                        'Auto-closed during migration: a newer active registration '
                        'already uses this %s.' % labels[field]
                    )
                reg.save(update_fields=['status', 'rejection_reason'])
            else:
                seen.add(key)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    # Non-atomic so the data normalization/dedupe commits before the unique
    # indexes are built (Postgres can't CREATE INDEX in the same transaction
    # that still has pending row-change trigger events).
    atomic = False

    dependencies = [
        ('vehicles', '0046_vehicleregistration_uniq_active_registration_plate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_normalize_and_dedupe, _noop),
        migrations.AddConstraint(
            model_name='vehicleregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted']), models.Q(('student_id', ''), _negated=True)), fields=('student_id',), name='uniq_active_registration_student_id'),
        ),
        migrations.AddConstraint(
            model_name='vehicleregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted']), models.Q(('employee_id', ''), _negated=True)), fields=('employee_id',), name='uniq_active_registration_employee_id'),
        ),
        migrations.AddConstraint(
            model_name='vehicleregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted']), models.Q(('drivers_license', ''), _negated=True)), fields=('drivers_license',), name='uniq_active_registration_drivers_license'),
        ),
    ]
