# Generated by Django 4.2.30 on 2026-07-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0046_vehicleregistration_driver_contact_and_more'),
        ('vehicles', '0047_parkingspace_points'),
        ('vehicles', '0047_vehicleregistration_uniq_active_registration_student_id_and_more'),
    ]

    operations = [
    ]
