# Generated by Django 4.2.30 on 2026-07-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0048_merge_20260706_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleregistration',
            name='fetcher_students',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='fetcher_type',
            field=models.CharField(blank=True, choices=[('drop_and_go', 'Fetcher / Drop & Go'), ('standby', 'Standby')], max_length=20),
        ),
    ]
