# Generated by Django 4.2.30 on 2026-07-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0049_vehicleregistration_fetcher_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='gate_id',
            field=models.CharField(blank=True, help_text='Required when assignment is Entry. Identifies which gate this camera covers.', max_length=10, null=True),
        ),
    ]
