# Generated by Django 6.0.5 on 2026-07-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0050_alter_camera_gate_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='camera',
            table='tbl_camera',
        ),
        migrations.AlterModelTable(
            name='event',
            table='tbl_event',
        ),
        migrations.AlterModelTable(
            name='parkingnotice',
            table='tbl_parking_notice',
        ),
        migrations.AlterModelTable(
            name='parkingspace',
            table='tbl_parking_space',
        ),
        migrations.AlterModelTable(
            name='parkingzone',
            table='tbl_parking_zone',
        ),
        migrations.AlterModelTable(
            name='referenceitem',
            table='tbl_reference_item',
        ),
        migrations.AlterModelTable(
            name='registrationperiod',
            table='tbl_registration_period',
        ),
        migrations.AlterModelTable(
            name='ruleconstraint',
            table='tbl_rule_constraint',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='tbl_supplier',
        ),
        migrations.AlterModelTable(
            name='supplierplate',
            table='tbl_supplier_plate',
        ),
        migrations.AlterModelTable(
            name='systemsettings',
            table='tbl_system_settings',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='tbl_vehicle',
        ),
        migrations.AlterModelTable(
            name='vehicleregistration',
            table='tbl_vehicle_registration',
        ),
    ]
