# Generated by Django 6.0.5 on 2026-07-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0051_alter_camera_table_alter_event_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingnotice',
            name='id',
            field=models.BigAutoField(db_column='parking_notice_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='id',
            field=models.BigAutoField(db_column='parking_space_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='id',
            field=models.BigAutoField(db_column='parking_zone_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrationperiod',
            name='id',
            field=models.BigAutoField(db_column='registration_period_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.BigAutoField(db_column='system_settings_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='id',
            field=models.BigAutoField(db_column='vehicle_registration_id', primary_key=True, serialize=False),
        ),
    ]
