# Generated by Django 6.0.5 on 2026-07-23 08:06

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0052_alter_parkingnotice_id_alter_parkingspace_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicleregistration',
            index=models.Index(fields=['-created_at'], name='vehreg_created_at'),
        ),
        migrations.AddIndex(
            model_name='vehicleregistration',
            index=models.Index(fields=['status', '-created_at'], name='vehreg_status_time'),
        ),
        migrations.AddIndex(
            model_name='vehicleregistration',
            index=models.Index(fields=['registrant_type'], name='vehreg_registrant_type'),
        ),
        migrations.AddIndex(
            model_name='vehicleregistration',
            index=django.contrib.postgres.indexes.GinIndex(fields=['campus_days'], name='vehreg_campus_days_gin'),
        ),
    ]
