# Generated by Django 4.2.30 on 2026-07-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0056_supplier_category_scheduledvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingnotice',
            name='id',
            field=models.BigAutoField(db_column='notice_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='id',
            field=models.BigAutoField(db_column='space_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='id',
            field=models.BigAutoField(db_column='zone_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrationperiod',
            name='id',
            field=models.BigAutoField(db_column='period_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scheduledvisit',
            name='id',
            field=models.BigAutoField(db_column='scheduled_visit_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.BigAutoField(db_column='settings_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='id',
            field=models.BigAutoField(db_column='registration_id', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='camera',
            table=None,
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.AlterModelTable(
            name='parkingnotice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='parkingspace',
            table=None,
        ),
        migrations.AlterModelTable(
            name='parkingzone',
            table=None,
        ),
        migrations.AlterModelTable(
            name='referenceitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='registrationperiod',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ruleconstraint',
            table=None,
        ),
        migrations.AlterModelTable(
            name='supplier',
            table=None,
        ),
        migrations.AlterModelTable(
            name='supplierplate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='systemsettings',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vehicleregistration',
            table=None,
        ),
    ]
