# Generated by Django 6.0.5 on 2026-07-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0056_supplier_category_scheduledvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledvisit',
            name='id',
            field=models.BigAutoField(db_column='scheduled_visit_id', primary_key=True, serialize=False),
        ),
    ]
