# Generated by Django 6.0.5 on 2026-07-31 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0058_restore_tbl_naming'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='account_expiry_days',
            field=models.IntegerField(default=0, help_text='Extra days (on top of months) before an owner account expires.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='account_expiry_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, vehicle-owner accounts auto-archive after the set duration.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='account_expiry_months',
            field=models.IntegerField(default=12, help_text='Months an owner account stays active after creation.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
