# Generated by Django 6.0.5 on 2026-08-01 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0059_systemsettings_account_expiry_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='conduction_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('plate_number', ''), _negated=True), fields=('plate_number',), name='uniq_vehicle_plate_number'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('conduction_number', ''), _negated=True), fields=('conduction_number',), name='uniq_vehicle_conduction_number'),
        ),
    ]
