# Generated by Django 6.0.5 on 2026-08-01 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0060_vehicle_conduction_number_alter_vehicle_plate_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicleregistration',
            name='uniq_active_registration_plate',
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='conduction_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='plate_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='vehicleregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted']), models.Q(('plate_number', ''), _negated=True)), fields=('plate_number',), name='uniq_active_registration_plate'),
        ),
        migrations.AddConstraint(
            model_name='vehicleregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted']), models.Q(('conduction_number', ''), _negated=True)), fields=('conduction_number',), name='uniq_active_registration_conduction'),
        ),
    ]
