# Generated by Django 6.0.5 on 2026-08-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0061_remove_vehicleregistration_uniq_active_registration_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='department_type',
            field=models.CharField(blank=True, choices=[('teaching', 'Teaching'), ('non_teaching', 'Non-Teaching'), ('services', 'Services'), ('cleaning', 'Cleaning')], max_length=20, null=True),
        ),
    ]
