# Generated by Django 6.0.5 on 2026-08-01 06:34

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0062_alter_vehicleregistration_department_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicleregistration',
            index=models.Index(django.db.models.functions.text.Upper(django.db.models.functions.text.Replace('plate_number', models.Value(' '), models.Value(''))), name='vehreg_plate_norm'),
        ),
        migrations.AddIndex(
            model_name='vehicleregistration',
            index=models.Index(django.db.models.functions.text.Lower('email'), name='vehreg_email_norm'),
        ),
    ]
