# Generated by Django 6.0.5 on 2026-08-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0063_vehicleregistration_vehreg_plate_norm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleregistration',
            name='department_type',
            field=models.CharField(blank=True, choices=[('teaching', 'Teaching'), ('non_teaching', 'Non-Teaching'), ('cleaning_services', 'Cleaning and Services')], max_length=20, null=True),
        ),
    ]
