# Generated by Django 6.0.5 on 2026-08-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0064_alter_vehicleregistration_department_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
