# Generated by Django 6.0.5 on 2026-08-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0065_alter_camera_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='password',
        ),
    ]
