# Generated by Django 6.0.5 on 2026-08-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0066_remove_camera_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
