# Generated by Django 6.0.5 on 2026-08-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0067_camera_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJobRun',
            fields=[
                ('id', models.BigAutoField(db_column='daily_job_run_id', primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=64)),
                ('run_date', models.DateField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'tbl_daily_job_run',
                'ordering': ['-run_date', 'job'],
                'constraints': [models.UniqueConstraint(fields=('job', 'run_date'), name='uniq_daily_job_per_day')],
            },
        ),
    ]
