# Generated by Django 6.0.5 on 2026-08-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0069_account_expiry_always_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='baseline_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingzone',
            name='baseline_image',
            field=models.ImageField(blank=True, null=True, upload_to='parking_baselines/'),
        ),
        migrations.AddField(
            model_name='parkingzone',
            name='occupancy_method',
            field=models.CharField(choices=[('ml', 'Vehicle detector (YOLO)'), ('classic', 'Baseline comparison (no ML)')], default='ml', help_text="How this zone decides a bay is taken. 'classic' compares each bay against an empty baseline and needs no detector; it falls back to the detector until a baseline is captured.", max_length=20),
        ),
    ]
