# Generated by Django 6.0.5 on 2026-08-12 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0070_parkingzone_baseline_captured_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='double_park_after_seconds',
            field=models.IntegerField(default=12, help_text='Seconds a vehicle must sit still across two or more bays before it is reported as double parking. Cannot be shorter than the parked threshold — a car cannot be badly parked before it counts as parked at all.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='parked_after_seconds',
            field=models.IntegerField(default=8, help_text='Seconds a vehicle must sit still before the camera counts it as parked and claims the bays it covers.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
