# Generated by Django 6.0.5 on 2026-08-19 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0072_schedule_choice_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_backup_frequency',
            field=models.CharField(choices=[('off', 'Off'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='off', help_text='How often the server takes a backup of system data by itself.', max_length=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_backup_keep',
            field=models.IntegerField(default=10, help_text='How many automatic backups to keep before the oldest is deleted. Pre-restore snapshots are never rotated away.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
