# Generated by Django 6.0.5 on 2026-08-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0077_fetcher_student_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='lens_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
