# Generated by Django 6.0.5 on 2026-08-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0078_parking_space_lens_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='lens_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
