# Generated by Django 6.0.5 on 2026-08-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0079_parking_zone_lens_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='detection_enabled',
            field=models.BooleanField(default=True, help_text="Run this zone's camera detector automatically. Turn off to pause it."),
        ),
    ]
