# Generated by Django 6.0.5 on 2026-09-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0080_parkingzone_detection_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='parking_share',
            field=models.CharField(choices=[('none', 'None — parking unaffected'), ('quarter', 'About 1/4 of parking'), ('third', 'About 1/3 of parking'), ('half', 'About 1/2 of parking'), ('two_thirds', 'About 2/3 of parking'), ('three_quarters', 'About 3/4 of parking'), ('full', 'All of parking')], default='none', help_text='How much of campus parking this event is expected to fill.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
