# Generated by Django 6.0.5 on 2026-09-12 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0081_event_end_time_event_parking_share_event_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationChangeRequest',
            fields=[
                ('id', models.BigAutoField(db_column='registration_change_request_id', primary_key=True, serialize=False)),
                ('changes', models.JSONField(default=dict)),
                ('previous', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending CDSO Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by Owner')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='vehicles.vehicleregistration')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_registration_change_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='changereq_status_time')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('registration',), name='uniq_pending_change_request_per_registration')],
            },
        ),
    ]
