# Generated by Django 4.2.30 on 2026-09-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0085_return_unpaid_accepted_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='report_approved_by_label',
            field=models.CharField(default='Approved by', help_text="Caption above the approver's signature.", max_length=60),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='report_approver_name',
            field=models.CharField(blank=True, default='', help_text="Name printed under 'Approved by' on every PDF report. Left blank, the report prints a ruled line to sign on.", max_length=150),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='report_approver_position',
            field=models.CharField(blank=True, default='Head, Campus Development and Security Office', help_text="Position printed beneath the approver's name.", max_length=150),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='report_prepared_by_label',
            field=models.CharField(default='Prepared by', help_text='Caption above the signature of whoever generated the report.', max_length=60),
        ),
    ]
