# Generated by Django 4.2.30 on 2026-09-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0086_report_signatories'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='report_preparer_name',
            field=models.CharField(blank=True, default='', help_text="Name printed under 'Prepared by' on every PDF report. Left blank, the report names whoever generated it.", max_length=150),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='report_preparer_position',
            field=models.CharField(blank=True, default='', help_text="Position printed beneath the preparer's name. Left blank, the report prints the generator's role.", max_length=150),
        ),
    ]
