# Generated by Django 4.2.30 on 2026-09-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0087_report_preparer_signatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='noise_stats',
            field=models.JSONField(blank=True, help_text='Measured noise of this bay while empty; sets its occupancy thresholds. Cleared to fall back to the conservative defaults.', null=True),
        ),
    ]
