# Generated by Django 4.2.30 on 2026-10-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0091_category_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(db_column='email_outbox_id', primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('recipients', models.CharField(blank=True, max_length=500)),
                ('message', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_attempt_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('delay_notified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_email_outbox',
                'ordering': ['next_attempt_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='email_outbox_due_idx')],
            },
        ),
    ]
