# Generated by Django 4.2.30 on 2026-10-01 12:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0092_email_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='scheduled_backup_day',
            field=models.SmallIntegerField(default=1, help_text='Monthly schedule only: day of the month. 29–31 fall on the last day of a shorter month.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='scheduled_backup_folder',
            field=models.CharField(blank=True, default='', help_text="Folder on the server computer the scheduled backups are written to. Blank uses the app's backups folder.", max_length=500),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='scheduled_backup_frequency',
            field=models.CharField(choices=[('off', 'Off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='off', help_text='Calendar schedule for backups saved to the chosen folder.', max_length=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='scheduled_backup_keep',
            field=models.IntegerField(default=12, help_text='How many scheduled backups to keep in that folder before the oldest is deleted.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='scheduled_backup_time',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Time of day (campus time) the scheduled backup is taken.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='scheduled_backup_weekday',
            field=models.SmallIntegerField(default=4, help_text='Weekly schedule only: 0 = Monday … 6 = Sunday.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
