# Generated by Django 4.2.30 on 2026-10-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0096_policy_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleconstraint',
            name='constraint_type',
            field=models.CharField(choices=[('student_vehicle', 'Student — Vehicle'), ('employee', 'Employee'), ('fetcher', 'Fetcher / Drop & Go / Driver'), ('supplier', 'Supplier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='fetcher_type',
            field=models.CharField(blank=True, choices=[('fetcher', 'Fetcher'), ('drop_and_go', 'Drop & Go'), ('standby', 'Driver (Whole Day)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicleregistration',
            name='registrant_type',
            field=models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('fetcher', 'Fetcher / Drop & Go / Driver')], max_length=20),
        ),
    ]
