# Generated by Django 4.2.30 on 2026-10-04 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0097_relabel_fetcher_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='occupant_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='occupant_noted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='occupant_noted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noted_parking_occupants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='occupant_plate',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
