# Generated by Django 4.2.30 on 2026-10-08 03:21

import django.core.validators
from django.db import migrations, models


def combine_schedules(apps, schema_editor):
    """Fold the two backup schedules into the one calendar schedule.

    The interval schedule (auto_backup_frequency: hourly/daily/weekly/monthly)
    is retired, and the calendar one no longer offers daily. Whatever was on
    becomes the nearest schedule the new list has:

      * calendar schedule already on: kept, with daily moved up to weekly
        (same weekday and time, so "daily at 5 PM" becomes "Fridays at 5 PM"
        with the default weekday).
      * only the interval schedule on: monthly stays monthly, anything faster
        becomes weekly, at the calendar schedule's stored time and day.

    The interval schedule is then switched off, so a server still running the
    older code (the campus clone until it updates) stops taking interval
    backups too instead of running both.
    """
    SystemSettings = apps.get_model('vehicles', 'SystemSettings')
    for cfg in SystemSettings.objects.all():
        freq = cfg.scheduled_backup_frequency
        if freq == 'daily':
            freq = 'weekly'
        elif freq == 'off' and cfg.auto_backup_frequency != 'off':
            freq = 'monthly' if cfg.auto_backup_frequency == 'monthly' else 'weekly'
        cfg.scheduled_backup_frequency = freq
        cfg.auto_backup_frequency = 'off'
        cfg.save(update_fields=['scheduled_backup_frequency', 'auto_backup_frequency'])


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0100_registrationperiod_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='scheduled_backup_month',
            field=models.SmallIntegerField(default=1, help_text='Yearly: the month of the year. Quarterly: any month of the cycle (1, 4, 7 and 10 are the same schedule).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='scheduled_backup_day',
            field=models.SmallIntegerField(default=1, help_text='Monthly, quarterly and yearly schedules: day of the month. 29–31 fall on the last day of a shorter month.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='scheduled_backup_frequency',
            field=models.CharField(choices=[('off', 'Off'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='off', help_text='Calendar schedule for automatic backups.', max_length=10),
        ),
        migrations.RunPython(combine_schedules, migrations.RunPython.noop),
    ]
