# Generated by Django 6.0.5 on 2026-06-09 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ml_samples/')),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('scan', 'Live Scan'), ('manual', 'Manual Label'), ('imported', 'Dataset Import')], default='scan', max_length=20)),
                ('status', models.CharField(choices=[('unlabeled', 'Unlabeled'), ('auto_labeled', 'Auto-Labeled'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unlabeled', max_length=20)),
                ('used_in_training', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-scanned_at']},
        ),
        migrations.AddField(
            model_name='accesslog',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
    ]
