# Generated by Django 4.2.29 on 2026-06-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0002_ml_training_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateRecognitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField(db_index=True)),
                ('plate_text', models.CharField(db_index=True, max_length=20)),
                ('detection_confidence', models.FloatField()),
                ('ocr_confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('snapshot_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['plate_text', '-timestamp'], name='plate_text_timestamp_idx'), models.Index(fields=['track_id'], name='track_id_idx')],
            },
        ),
    ]
