# Generated by Django 4.2.29 on 2026-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0003_add_plate_recognition_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='bicycle, e_bike, electric_scooter for unplated vehicles', max_length=20),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
