# Generated by Django 4.2.30 on 2026-06-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0008_accesslog_entry_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorpass',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='digital_id_used',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='status',
            field=models.CharField(choices=[('authorized', 'Authorized'), ('denied', 'Denied'), ('wrong_day', 'Wrong Day'), ('unknown', 'Unknown Plate'), ('unreadable', 'Unreadable'), ('exited', 'Exited')], max_length=20),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
