# Generated by Django 6.0.5 on 2026-07-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0012_accesslog_on_duty_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='id',
            field=models.BigAutoField(db_column='access_log_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guardshift',
            name='id',
            field=models.BigAutoField(db_column='shift_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mltrainingsample',
            name='id',
            field=models.BigAutoField(db_column='sample_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='office',
            name='id',
            field=models.BigAutoField(db_column='office_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='platerecognitionrecord',
            name='id',
            field=models.BigAutoField(db_column='record_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='id',
            field=models.BigAutoField(db_column='visitor_pass_id', primary_key=True, serialize=False),
        ),
    ]
