# Generated by Django 4.2.30 on 2026-07-06 11:28

from django.db import migrations, models


def seed_gates(apps, schema_editor):
    Gate = apps.get_model('scanning', 'Gate')
    Gate.objects.get_or_create(gate_id='gate1', defaults={'label': 'Gate 1 — Main Entrance'})
    Gate.objects.get_or_create(gate_id='gate4', defaults={'label': 'Gate 4 — Side Entrance'})


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0013_alter_accesslog_id_alter_guardshift_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(db_column='gate_pk', primary_key=True, serialize=False)),
                ('gate_id', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['gate_id'],
            },
        ),
        migrations.RunPython(seed_gates, migrations.RunPython.noop),
    ]
