# Generated by Django 4.2.30 on 2026-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0014_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorpass',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
