# Generated by Django 6.0.5 on 2026-07-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0015_visitorpass_printed_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accesslog',
            table='tbl_access_log',
        ),
        migrations.AlterModelTable(
            name='gate',
            table='tbl_gate',
        ),
        migrations.AlterModelTable(
            name='guardshift',
            table='tbl_guard_shift',
        ),
        migrations.AlterModelTable(
            name='mltrainingsample',
            table='tbl_ml_training_sample',
        ),
        migrations.AlterModelTable(
            name='office',
            table='tbl_office',
        ),
        migrations.AlterModelTable(
            name='platerecognitionrecord',
            table='tbl_plate_recognition_record',
        ),
        migrations.AlterModelTable(
            name='visitorpass',
            table='tbl_visitor_pass',
        ),
    ]
