# Generated by Django 6.0.5 on 2026-07-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0016_alter_accesslog_table_alter_gate_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardshift',
            name='id',
            field=models.BigAutoField(db_column='guard_shift_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mltrainingsample',
            name='id',
            field=models.BigAutoField(db_column='ml_training_sample_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='platerecognitionrecord',
            name='id',
            field=models.BigAutoField(db_column='plate_recognition_record_id', primary_key=True, serialize=False),
        ),
    ]
