# Generated by Django 4.2.30 on 2026-07-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0017_alter_guardshift_id_alter_mltrainingsample_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardshift',
            name='id',
            field=models.BigAutoField(db_column='shift_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mltrainingsample',
            name='id',
            field=models.BigAutoField(db_column='sample_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='platerecognitionrecord',
            name='id',
            field=models.BigAutoField(db_column='record_id', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='accesslog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='guardshift',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mltrainingsample',
            table=None,
        ),
        migrations.AlterModelTable(
            name='office',
            table=None,
        ),
        migrations.AlterModelTable(
            name='platerecognitionrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='visitorpass',
            table=None,
        ),
    ]
