# Generated by Django 6.0.5 on 2026-07-23 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0017_alter_guardshift_id_alter_mltrainingsample_id_and_more'),
        ('vehicles', '0053_vehicleregistration_vehreg_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['plate_number', 'status', '-scanned_at'], name='accesslog_plate_status_time'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['-scanned_at'], name='accesslog_scanned_at'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['status', '-scanned_at'], name='accesslog_status_time'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['scanned_by', '-scanned_at'], name='accesslog_scanned_by_time'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['vehicle', '-scanned_at'], name='accesslog_vehicle_time'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['gate_id', '-scanned_at'], name='accesslog_gate_time'),
        ),
        migrations.AddIndex(
            model_name='guardshift',
            index=models.Index(fields=['guard', '-clocked_in_at'], name='guardshift_guard_time'),
        ),
        migrations.AddIndex(
            model_name='guardshift',
            index=models.Index(fields=['gate', '-clocked_in_at'], name='guardshift_gate_time'),
        ),
        migrations.AddIndex(
            model_name='guardshift',
            index=models.Index(fields=['clocked_out_at'], name='guardshift_clocked_out'),
        ),
        migrations.AddIndex(
            model_name='mltrainingsample',
            index=models.Index(fields=['-created_at'], name='mlsample_created_at'),
        ),
        migrations.AddIndex(
            model_name='mltrainingsample',
            index=models.Index(fields=['status', '-created_at'], name='mlsample_status_time'),
        ),
        migrations.AddIndex(
            model_name='visitorpass',
            index=models.Index(fields=['status', 'valid_date'], name='visitorpass_status_date'),
        ),
    ]
