# Generated by Django 6.0.5 on 2026-09-12 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0019_restore_tbl_naming'),
        ('vehicles', '0081_event_end_time_event_parking_share_event_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='entrant_category',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee'), ('fetcher', 'Fetcher / Drop & Go'), ('visitor', 'Visitor'), ('supplier', 'Supplier'), ('unknown', 'Unregistered')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='entry_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='is_unrecognized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['entrant_category', '-scanned_at'], name='accesslog_category_time'),
        ),
    ]
