# Generated by Django 6.0.5 on 2026-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0020_accesslog_driver_name_accesslog_entrant_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorpass',
            name='visitor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
