# Generated by Django 4.2.30 on 2026-09-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0023_accesslog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorpass',
            name='conduction_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
