# Generated by Django 4.2.30 on 2026-09-26 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0089_scheduled_visit_arrival'),
        ('scanning', '0024_visitorpass_conduction_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorpass',
            name='scheduled_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_passes', to='vehicles.scheduledvisit'),
        ),
    ]
