# Generated by Django 4.2.30 on 2026-09-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0025_scheduled_visit_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='digital_id_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
