# Generated by Django 4.2.30 on 2026-09-27 08:17

from datetime import datetime, time, timedelta

from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


def link_past_entries(apps, schema_editor):
    """Give entries logged before this field existed the booking they came in
    under, so the old records read "Scheduled Entry" too. Mirrors the live
    rule in scanning.signals: an authorized entry on a day its plate (or the
    vehicle's conduction number) was booked, archived bookings excluded; a
    visitor slip printed from a booking is linked to that booking outright."""
    from django.utils import timezone

    AccessLog = apps.get_model('scanning', 'AccessLog')
    ScheduledVisit = apps.get_model('vehicles', 'ScheduledVisit')
    VisitorPass = apps.get_model('scanning', 'VisitorPass')
    AUTHORIZED = 'authorized'

    # 1. Visitor slips checked in from a booking: the entry is logged when the
    #    slip prints, under the pass's plate — which may not be the booked one.
    for pass_ in VisitorPass.objects.filter(scheduled_visit__isnull=False,
                                            printed_at__isnull=False):
        entry = (AccessLog.objects
                 .filter(plate_number=pass_.plate_number, status=AUTHORIZED,
                         scheduled_visit__isnull=True,
                         scanned_at__gte=pass_.printed_at - timedelta(seconds=5),
                         scanned_at__lte=pass_.printed_at + timedelta(minutes=1))
                 .order_by('scanned_at').first())
        if entry:
            AccessLog.objects.filter(pk=entry.pk).update(scheduled_visit_id=pass_.scheduled_visit_id)

    # 2. Everything else, by plate on the booked day (campus-local).
    for visit in ScheduledVisit.objects.filter(archived_at__isnull=True).exclude(plate_number=''):
        start = timezone.make_aware(datetime.combine(visit.expected_date, time.min))
        end = start + timedelta(days=1)
        (AccessLog.objects
         .filter(Q(plate_number=visit.plate_number)
                 | Q(vehicle__plate_number=visit.plate_number)
                 | Q(vehicle__conduction_number=visit.plate_number),
                 status=AUTHORIZED, scheduled_visit__isnull=True,
                 scanned_at__gte=start, scanned_at__lt=end)
         .update(scheduled_visit_id=visit.pk))


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0090_scheduled_visit_archive'),
        ('scanning', '0026_accesslog_digital_id_used_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='scheduled_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='vehicles.scheduledvisit'),
        ),
        # Reversing drops the column, which takes the links with it.
        migrations.RunPython(link_past_entries, migrations.RunPython.noop),
    ]
