# Generated by Django 4.2.30 on 2026-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0028_accesslog_cross_gate_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='entrant_category',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee'), ('fetcher', 'Fetcher / Drop & Go / Parent'), ('visitor', 'Visitor'), ('supplier', 'Supplier'), ('event', 'Event Organizer'), ('unknown', 'Unregistered')], default='', max_length=20),
        ),
    ]
