# Generated by Django 4.2.30 on 2026-10-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0029_relabel_fetcher_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='entrant_category',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employee', 'Employee'), ('fetcher', 'Fetcher / Drop & Go / Driver'), ('visitor', 'Visitor'), ('supplier', 'Supplier'), ('event', 'Event Organizer'), ('unknown', 'Unregistered')], default='', max_length=20),
        ),
    ]
