# Generated by Django 4.2.30 on 2026-06-30 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('violations', '0003_violation_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_violations', to=settings.AUTH_USER_MODEL),
        ),
    ]
