# Generated by Django 6.0.5 on 2026-07-02 05:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0005_violation_offense_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
