# Generated by Django 6.0.5 on 2026-07-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0007_violation_on_duty_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='id',
            field=models.BigAutoField(db_column='violation_id', primary_key=True, serialize=False),
        ),
    ]
