# Generated by Django 6.0.5 on 2026-07-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0008_alter_violation_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='violation',
            table='tbl_violation',
        ),
    ]
