# Generated by Django 4.2.30 on 2026-07-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0009_alter_violation_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='violation',
            table=None,
        ),
    ]
