# Generated by Django 6.0.5 on 2026-07-23 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0053_vehicleregistration_vehreg_created_at_and_more'),
        ('violations', '0009_alter_violation_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['vehicle', 'violation_type', '-issued_at'], name='violation_vehicle_type_time'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['-issued_at'], name='violation_issued_at'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['status', '-issued_at'], name='violation_status_time'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['issued_by', '-issued_at'], name='violation_issued_by_time'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['is_resolved'], name='violation_is_resolved'),
        ),
    ]
