# Generated by Django 6.0.5 on 2026-07-31 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0011_restore_tbl_naming'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='lifted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='lifted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_violations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violation',
            name='lifted_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('warning', 'Warning'), ('fee_imposed', 'Fee Imposed'), ('cleared', 'Cleared'), ('lifted', 'Lifted (False Alarm)')], default='warning', max_length=20),
        ),
    ]
