# Generated by Django 6.0.5 on 2026-08-05 07:00
#
# Schema only. The identity backfill lives in 0014 and must stay there.
#
# Postgres refuses to ALTER or CREATE INDEX on a table that has pending foreign
# key trigger events, and bulk UPDATEs queue exactly those. With the data step
# in this file the migration fails whichever way it is ordered:
#
#   backfill, then AlterField  -> cannot ALTER TABLE "tbl_violation"
#                                 because it has pending trigger events
#   AlterField, then backfill  -> cannot CREATE INDEX "tbl_violation"
#                                 because it has pending trigger events
#
# The second one is the surprise: Django collects index creation into
# `deferred_sql` and runs it when the schema editor exits, which is *after* the
# RunPython step, so moving the data operation later does not get it out of the
# way. Separate migrations are the only clean answer.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0070_parkingzone_baseline_captured_at_and_more'),
        ('violations', '0012_violation_lifted_at_violation_lifted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='conduction_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='violation',
            name='owner_email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='violation',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='violation',
            name='plate_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='violation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='vehicles.vehicle'),
        ),
    ]
