# Generated by Django 6.0.5 on 2026-08-16 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0014_backfill_violation_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(choices=[('warning', 'Warning'), ('fee_imposed', 'Fee Imposed (Legacy)'), ('cleared', 'Cleared'), ('lifted', 'Lifted (False Alarm)')], default='warning', max_length=20),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('unauthorized_entry', 'Unauthorized Entry'), ('double_parking', 'Double Parking'), ('time_exceed', 'Time Exceed'), ('no_sticker', 'No Sticker'), ('expired_registration', 'Expired Registration'), ('confiscated_activity', 'Activity While Confiscated'), ('unauthorized', 'Unauthorized (Legacy)'), ('other', 'Other')], max_length=30),
        ),
    ]
