# Generated by Django 4.2.30 on 2026-10-05 08:26

import re

from django.db import migrations, models


# Every gate path wrote the overstay into the notes as "... by N min" before
# it had a column of its own; read it back from there.
_BY_MINUTES = re.compile(r'\bby (\d+) min\b')


def backfill_overstay_minutes(apps, schema_editor):
    Violation = apps.get_model('violations', 'Violation')
    for row in Violation.objects.filter(violation_type='time_exceed', overstay_minutes__isnull=True):
        found = _BY_MINUTES.search(row.notes or '')
        if found:
            Violation.objects.filter(pk=row.pk).update(overstay_minutes=int(found.group(1)))


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0017_remove_violation_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='overstay_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('unauthorized_entry', 'Unauthorized Entry'), ('double_parking', 'Double Parking'), ('time_exceed', 'Overstaying'), ('no_sticker', 'No Sticker'), ('expired_registration', 'Expired Registration'), ('confiscated_activity', 'Activity While Confiscated'), ('unauthorized', 'Unauthorized (Legacy)'), ('other', 'Other')], max_length=30),
        ),
        migrations.RunPython(backfill_overstay_minutes, migrations.RunPython.noop),
    ]
